/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Creator = IDL.Record({
  'bio' : IDL.Text,
  'portfolio' : IDL.Text,
  'name' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const Time = IDL.Int;
export const SubmissionType = IDL.Variant({
  'creator' : IDL.Null,
  'brand' : IDL.Null,
});
export const Brand = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const Submission = IDL.Record({
  'creator' : IDL.Opt(Creator),
  'timestamp' : Time,
  'submissionType' : SubmissionType,
  'brand' : IDL.Opt(Brand),
});
export const BrandForm = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'website' : IDL.Text,
  'contactEmail' : IDL.Text,
});
export const CreatorForm = IDL.Record({
  'bio' : IDL.Text,
  'portfolio' : IDL.Text,
  'name' : IDL.Text,
  'contactEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getSubmission' : IDL.Func([IDL.Text], [Submission], ['query']),
  'submitBrand' : IDL.Func([BrandForm], [IDL.Text], []),
  'submitCreator' : IDL.Func([CreatorForm], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Creator = IDL.Record({
    'bio' : IDL.Text,
    'portfolio' : IDL.Text,
    'name' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const Time = IDL.Int;
  const SubmissionType = IDL.Variant({
    'creator' : IDL.Null,
    'brand' : IDL.Null,
  });
  const Brand = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const Submission = IDL.Record({
    'creator' : IDL.Opt(Creator),
    'timestamp' : Time,
    'submissionType' : SubmissionType,
    'brand' : IDL.Opt(Brand),
  });
  const BrandForm = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'website' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  const CreatorForm = IDL.Record({
    'bio' : IDL.Text,
    'portfolio' : IDL.Text,
    'name' : IDL.Text,
    'contactEmail' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getSubmission' : IDL.Func([IDL.Text], [Submission], ['query']),
    'submitBrand' : IDL.Func([BrandForm], [IDL.Text], []),
    'submitCreator' : IDL.Func([CreatorForm], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };