/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Brand {
  'name' : string,
  'description' : string,
  'website' : string,
  'contactEmail' : string,
}
export interface BrandForm {
  'name' : string,
  'description' : string,
  'website' : string,
  'contactEmail' : string,
}
export interface Creator {
  'bio' : string,
  'portfolio' : string,
  'name' : string,
  'contactEmail' : string,
}
export interface CreatorForm {
  'bio' : string,
  'portfolio' : string,
  'name' : string,
  'contactEmail' : string,
}
export interface Submission {
  'creator' : [] | [Creator],
  'timestamp' : Time,
  'submissionType' : SubmissionType,
  'brand' : [] | [Brand],
}
export type SubmissionType = { 'creator' : null } |
  { 'brand' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getSubmission' : ActorMethod<[string], Submission>,
  'submitBrand' : ActorMethod<[BrandForm], string>,
  'submitCreator' : ActorMethod<[CreatorForm], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];